In [ ]:
!pip install tensorflow keras nltk spacy-stanza

In [19]:
import pickle
import numpy as np
from keras.models import load_model
model = load_model('chatbot_model.h5')
# model = load_model('model_checkpoint.h5')

import json
import random

from utils import *


[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\josel\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\josel\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\josel\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\josel\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


2021-12-23 17:13:26 INFO: Downloading default packages for language: es (Spanish)...
2021-12-23 17:13:27 INFO: File exists: C:\Users\josel\stanza_resources\es\default.zip.
2021-12-23 17:13:31 INFO: Finished downloading models and saved to C:\Users\josel\stanza_resources.


NameError: name 'spacy_stanza' is not defined

In [15]:
intents = json.loads(open('intents.json').read())
words = pickle.load(open('words.pkl','rb'))
classes = pickle.load(open('classes.pkl','rb'))

In [ ]:
classes

In [13]:
def bow(sentence, words, show_details=True):
    # tokenize the pattern
    sentence_words = tokenize(final_sentence(sentence))
    print(sentence_words)
    # bag of words - matrix of N words, vocabulary matrix
    bag = [0]*len(words) 
    for s in sentence_words:
        for i,w in enumerate(words):
            if w == s: 
                # assign 1 if current word is in the vocabulary position
                bag[i] = 1
                if show_details:
                    print(f'found in bag: {w}')
    print(np.array(bag))
    return(np.array(bag))
def predict_class(sentence, model):
    # filter out predictions below a threshold
    p = bow(sentence, words)
    return_list = []
    if np.any(p):
        res = model.predict(np.array([p]))[0]
        ERROR_THRESHOLD = 0.0
        results = [[i,r] for i,r in enumerate(res) if r>ERROR_THRESHOLD]
        # sort by strength of probability
        results.sort(key=lambda x: x[1], reverse=True)
        for r in results:
            return_list.append({"intent": classes[r[0]], "probability": str(r[1])})
    else:
        return_list.append({"intent": 'sin respuesta', "probability": '90.0'})
    print(return_list)
    return return_list

In [11]:
def getResponse(ints, intents_json):
    tag = ints[0]['intent']
    list_of_intents = intents_json['intents']
    for i in list_of_intents:
        if(i['tag']== tag):
            result = random.choice(i['responses'])
            break
    return result
def chatbot_response(text):
    ints = predict_class(text.lower(), model)
    res = getResponse(ints, intents)
    return res

In [16]:
chatbot_response("alo")

NameError: name 'tokenize' is not defined

In [3]:
chatbot_response("HOLA")

NameError: name 'chatbot_response' is not defined

In [10]:
chatbot_response("adios")

['adios']
found in bag: adios
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[{'intent': 'despedida', 'probability': '0.634675'}, {'intent': 'alimentos_sanos', 'probability': '0.15667336'}, {'intent': 'saludo', 'probability': '0.0878203'}, {'intent': 'opciones', 'probability': '0.06515408'}, {'intent': 'alimentos_no_sanos', 'probability': '0.055677205'}]


'Hasta la próxima'

In [11]:
chatbot_response("QUIERO COMER ATUN")

['querer', 'comer', 'proteina']
found in bag: proteina
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
[{'intent': 'alimentos_sanos', 'probability': '0.9154304'}, {'intent': 'alimentos_no_sanos', 'probability': '0.032238916'}, {'intent': 'saludo', 'probability': '0.025358241'}, {'intent': 'despedida', 'probability': '0.018851126'}, {'intent': 'opciones', 'probability': '0.008121277'}]


'El alimento mencionado es un alimento sano, te ayudará a ser un niño saludable'

In [12]:
chatbot_response("QUIERO COMER DULCES")

['querer', 'comer', 'dulce']
found in bag: dulce
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[{'intent': 'alimentos_no_sanos', 'probability': '0.37260658'}, {'intent': 'alimentos_sanos', 'probability': '0.28144014'}, {'intent': 'despedida', 'probability': '0.16545594'}, {'intent': 'saludo', 'probability': '0.10278233'}, {'intent': 'opciones', 'probability': '0.07771496'}]


'Estás mencionando un alimento poco saludable, no deberías comer mucho de eso'

In [13]:
chatbot_response("qué haces")

['hacer']
found in bag: hacer
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[{'intent': 'opciones', 'probability': '0.57060224'}, {'intent': 'alimentos_sanos', 'probability': '0.21452497'}, {'intent': 'alimentos_no_sanos', 'probability': '0.13023484'}, {'intent': 'saludo', 'probability': '0.0574299'}, {'intent': 'despedida', 'probability': '0.027208036'}]


'Puedo ayudarte a verificar si una alimento es sano o no'

In [14]:
chatbot_response("QUIERO COMER")

['querer', 'comer']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[{'intent': 'sin respuesta', 'probability': '90.0'}]


'Lo siento no te entiendo, recuerda mencionar un solo alimento para asesorarte'

In [17]:
chatbot_response("QUIERO COMER CERDO")

['querer', 'comer', 'proteina']
found in bag: proteina
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
[{'intent': 'alimentos_sanos', 'probability': '0.9154304'}, {'intent': 'alimentos_no_sanos', 'probability': '0.032238916'}, {'intent': 'saludo', 'probability': '0.025358241'}, {'intent': 'despedida', 'probability': '0.018851126'}, {'intent': 'opciones', 'probability': '0.008121277'}]


'El alimento mencionado es un alimento sano, te ayudará a ser un niño saludable'